// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/blueworrybear/lineBot/config"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeApplication(cfg *config.Config, db *gorm.DB) (application, error) {
	databaseService := provideDatabaseService(db)
	userStore := provideUserStore(databaseService)
	chatStore := provideChatStore(databaseService)
	questionStore := provideQuestionStore(databaseService)
	chatService := provideChatService(cfg, userStore, chatStore)
	questionService := provideQuestionService(userStore, questionStore, chatService)
	routers := provideRouter(cfg, userStore, chatStore, questionStore, chatService, questionService)
	mainApplication := newApplication(routers, databaseService)
	return mainApplication, nil
}
